--
-- BACKUP BASE DE DATOS: SABOR PAISA
-- Sistema de Gestión de Restaurantes
-- Fecha: Noviembre 2025
--

-- ========================================
-- CREACIÓN DE LA BASE DE DATOS
-- ========================================

-- Crear la base de datos (ejecutar como superusuario)
-- CREATE DATABASE saborpaisa;
-- \c saborpaisa;

-- ========================================
-- CREACIÓN DE TABLAS
-- ========================================

-- 1. Tabla LOCAL
CREATE TABLE IF NOT EXISTS LOCAL (
    ID_LOCAL SERIAL PRIMARY KEY,
    NOMBRE_COMERCIAL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    TELEFONO VARCHAR(15),
    GERENTE VARCHAR(100),
    HORA_APERTURA TIME,
    HORA_CIERRE TIME
);

-- 2. Tabla MENU
CREATE TABLE IF NOT EXISTS MENU (
    ID_MENU SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50),
    PRECIO_BASE DECIMAL(10, 2) NOT NULL,
    DESCRIPCION TEXT,
    DISPONIBILIDAD BOOLEAN DEFAULT TRUE
);

-- 3. Tabla PROVEEDOR
CREATE TABLE IF NOT EXISTS PROVEEDOR (
    ID_PROVEEDOR SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NIT VARCHAR(20) UNIQUE,
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(150)
);

-- 4. Tabla INGREDIENTE
CREATE TABLE IF NOT EXISTS INGREDIENTE (
    ID_INGREDIENTE SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    UNIDAD_MEDIDA VARCHAR(20),
    CANTIDAD_INVENTARIO DECIMAL(10, 2) DEFAULT 0,
    CANTIDAD_MINIMA DECIMAL(10, 2),
    CANTIDAD_MAXIMA DECIMAL(10, 2)
);

-- 5. Tabla CLIENTEFRECUENTE
CREATE TABLE IF NOT EXISTS CLIENTEFRECUENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR(150) NOT NULL,
    DOCUMENTO VARCHAR(20) UNIQUE NOT NULL,
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(15),
    FECHA_INSCRIPCION DATE DEFAULT CURRENT_DATE,
    PUNTOS_ACUMULADOS INT DEFAULT 0
);

-- 6. Tabla PEDIDO (Encabezado)
CREATE TABLE IF NOT EXISTS PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_CLIENTE INT,
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_LOCAL INT NOT NULL,
    VALOR_TOTAL DECIMAL(12, 2) NOT NULL,
    TIPO_PAGO VARCHAR(20) CHECK (TIPO_PAGO IN ('efectivo', 'tarjeta', 'transferencia')),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTEFRECUENTE (ID_CLIENTE),
    FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL (ID_LOCAL) ON DELETE CASCADE
);

-- 7. Tabla DETALLEPEDIDO
CREATE TABLE IF NOT EXISTS DETALLEPEDIDO (
    ID_DETALLE SERIAL PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_MENU INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(12, 2) GENERATED ALWAYS AS (CANTIDAD * PRECIO_UNITARIO) STORED,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO) ON DELETE CASCADE,
    FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)
);

-- 8. Tabla COMPRA (Encabezado)
CREATE TABLE IF NOT EXISTS COMPRA (
    ID_COMPRA SERIAL PRIMARY KEY,
    ID_PROVEEDOR INT NOT NULL,
    FECHA_COMPRA DATE DEFAULT CURRENT_DATE,
    VALOR_TOTAL DECIMAL(12, 2) NOT NULL,
    TIPO_PAGO VARCHAR(20),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
);

-- 9. Tabla DETALLECOMPRA
CREATE TABLE IF NOT EXISTS DETALLECOMPRA (
    ID_DETALLE_COMPRA SERIAL PRIMARY KEY,
    ID_COMPRA INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,
    CANTIDAD DECIMAL(10, 2) NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(12, 2) GENERATED ALWAYS AS (CANTIDAD * PRECIO_UNITARIO) STORED,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA) ON DELETE CASCADE,
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE)
);

-- 10. Tabla INGREDIENTEPRODUCTO (Relación N:M)
CREATE TABLE IF NOT EXISTS INGREDIENTEPRODUCTO (
    ID_INGREDIENTE INT NOT NULL,
    ID_MENU INT NOT NULL,
    CANTIDAD_REQUERIDA DECIMAL(8, 2) NOT NULL,
    PRIMARY KEY (ID_INGREDIENTE, ID_MENU),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE),
    FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU)
);

-- 11. Tabla PROVEEDORINGREDIENTE (Relación N:M)
CREATE TABLE IF NOT EXISTS PROVEEDORINGREDIENTE (
    ID_PROVEEDOR INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,
    PRECIO_UNITARIO_ACTUAL DECIMAL(10, 2),
    PRIMARY KEY (ID_PROVEEDOR, ID_INGREDIENTE),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE)
);

-- ========================================
-- INSERCIÓN DE DATOS DE PRUEBA
-- ========================================

-- INSERTAR 5 LOCALES
INSERT INTO LOCAL (NOMBRE_COMERCIAL, DIRECCION, TELEFONO, GERENTE, HORA_APERTURA, HORA_CIERRE) VALUES
('Sabor Paisa Centro', 'Cra 43A #7-50, La Candelaria', '6041234567', 'Ana María Gómez', '07:00:00', '22:00:00'),
('Café Paisa Laureles', 'Cra 70 #Circular 1-50, Laureles', '6049876543', 'Luis Fernando Martínez', '06:30:00', '21:00:00'),
('Sabor Paisa Poblado', 'Calle 10 #43B-50, El Poblado', '6043219876', 'Carolina Ramírez', '11:00:00', '23:00:00'),
('Arepa & Café Envigado', 'Cra 43A #38 Sur-50, Envigado', '6045554321', 'Diego Alejandro López', '08:00:00', '20:00:00'),
('Sabor Paisa Bello', 'Calle 45 #52-30, Centro de Bello', '6046667890', 'María José Herrera', '09:00:00', '21:30:00');

-- INSERTAR 5 PRODUCTOS (MENÚ)
INSERT INTO MENU (NOMBRE, CATEGORIA, PRECIO_BASE, DESCRIPCION, DISPONIBILIDAD) VALUES
('Bandeja Paisa', 'plato fuerte', 38000.00, 'Frijoles, arroz, carne molida, chicharrón, huevo, aguacate', TRUE),
('Café Americano', 'café', 5500.00, 'Café negro clásico', TRUE),
('Jugo de Mango', 'jugo', 8500.00, 'Jugo natural de mango con agua', TRUE),
('Empanadas Antioqueñas', 'entrada', 12000.00, '3 empanadas de carne o pollo', TRUE),
('Arepita con Queso', 'entrada', 7000.00, 'Arepa pequeña con queso derretido', FALSE);

-- INSERTAR 5 PROVEEDORES
INSERT INTO PROVEEDOR (NOMBRE, NIT, TELEFONO, DIRECCION) VALUES
('DistriCarne S.A.', '900123456-1', '6045551234', 'Calle 10 #25-30, Guayabal'),
('Frutas del Valle', '901234567-2', '6046669876', 'Carrera 80 #12-45, Itagüí'),
('Lácteos La Vaquita', '902345678-3', '6047778901', 'Calle 50 #60-20, Belén'),
('Café de la Montaña', '903456789-4', '6048889012', 'Cra 43A #1-50, Centro'),
('Verduras Frescas', '904567890-5', '6049990123', 'Calle 30 #70-15, Laureles');

-- INSERTAR 5 INGREDIENTES
INSERT INTO INGREDIENTE (NOMBRE, UNIDAD_MEDIDA, CANTIDAD_INVENTARIO, CANTIDAD_MINIMA, CANTIDAD_MAXIMA) VALUES
('Frijol rojo', 'gramos', 8000.00, 1000.00, 15000.00),
('Carne molida', 'gramos', 5000.00, 800.00, 10000.00),
('Mango', 'unidades', 120.00, 20.00, 300.00),
('Queso campesino', 'gramos', 3000.00, 500.00, 6000.00),
('Café en grano', 'gramos', 4000.00, 1000.00, 8000.00);

-- INSERTAR 5 CLIENTES FRECUENTES
INSERT INTO CLIENTEFRECUENTE (NOMBRE_COMPLETO, DOCUMENTO, CORREO, TELEFONO, PUNTOS_ACUMULADOS) VALUES
('Carlos Andrés Pérez', '12345678', 'carlos.perez@mail.com', '3001234567', 250),
('Laura Valentina Gómez', '87654321', 'laura.gomez@mail.com', '3009876543', 180),
('Juan José Ramírez', '11223344', 'juan.ramirez@mail.com', '3015556677', 90),
('María Alejandra López', '99887766', 'maria.lopez@mail.com', '3024445566', 320),
('Diego Fernando Herrera', '55443322', 'diego.herrera@mail.com', '3036667788', 150);

-- INSERTAR 5 PEDIDOS
INSERT INTO PEDIDO (ID_CLIENTE, ID_LOCAL, VALOR_TOTAL, TIPO_PAGO) VALUES
(1, 1, 43500.00, 'tarjeta'),
(2, 2, 14000.00, 'efectivo'),
(NULL, 3, 38000.00, 'transferencia'),
(4, 4, 27000.00, 'tarjeta'),
(5, 1, 12000.00, 'efectivo');

-- INSERTAR 5 DETALLES DE PEDIDO
INSERT INTO DETALLEPEDIDO (ID_PEDIDO, ID_MENU, CANTIDAD, PRECIO_UNITARIO) VALUES
(1, 1, 1, 38000.00),
(1, 2, 1, 5500.00),
(2, 2, 2, 5500.00),
(3, 1, 1, 38000.00),
(4, 4, 2, 12000.00);

-- INSERTAR 5 COMPRAS
INSERT INTO COMPRA (ID_PROVEEDOR, FECHA_COMPRA, VALOR_TOTAL, TIPO_PAGO) VALUES
(1, '2025-10-28', 800000.00, 'transferencia'),
(2, '2025-10-29', 240000.00, 'efectivo'),
(3, '2025-10-30', 360000.00, 'transferencia'),
(4, '2025-10-31', 480000.00, 'tarjeta'),
(5, '2025-11-01', 150000.00, 'transferencia');

-- INSERTAR 5 DETALLES DE COMPRA
INSERT INTO DETALLECOMPRA (ID_COMPRA, ID_INGREDIENTE, CANTIDAD, PRECIO_UNITARIO) VALUES
(1, 2, 100.00, 8000.00),
(2, 3, 200.00, 1200.00),
(3, 4, 120.00, 3000.00),
(4, 5, 160.00, 3000.00),
(5, 1, 150.00, 1000.00);

-- INSERTAR RELACIONES INGREDIENTE → PRODUCTO
INSERT INTO INGREDIENTEPRODUCTO (ID_INGREDIENTE, ID_MENU, CANTIDAD_REQUERIDA) VALUES
(1, 1, 200.00),
(2, 1, 150.00),
(3, 3, 1.50),
(4, 5, 50.00),
(5, 2, 12.00);

-- INSERTAR RELACIONES PROVEEDOR → INGREDIENTE
INSERT INTO PROVEEDORINGREDIENTE (ID_PROVEEDOR, ID_INGREDIENTE, PRECIO_UNITARIO_ACTUAL) VALUES
(1, 2, 8000.00),
(2, 3, 1200.00),
(3, 4, 3000.00),
(4, 5, 3000.00),
(5, 1, 1000.00);

-- ========================================
-- CONSULTAS DE VERIFICACIÓN
-- ========================================

-- Verificar datos de locales
SELECT * FROM LOCAL ORDER BY ID_LOCAL;

-- Contar registros por tabla
SELECT 'LOCAL' AS tabla, COUNT(*) AS total FROM LOCAL
UNION ALL
SELECT 'MENU', COUNT(*) FROM MENU
UNION ALL
SELECT 'PROVEEDOR', COUNT(*) FROM PROVEEDOR
UNION ALL
SELECT 'INGREDIENTE', COUNT(*) FROM INGREDIENTE
UNION ALL
SELECT 'CLIENTEFRECUENTE', COUNT(*) FROM CLIENTEFRECUENTE;

-- ========================================
-- FIN DEL BACKUP
-- ========================================
